import { Vehicle, TourPackage, PricingRules, Review } from '../types';

export const BUSINESS_INFO = {
  name: 'ADVIK TOURS AND TRAVELS',
  tagline: 'Reliable Travel. Comfortable Journeys.',
  description: 'Your premier travel partner for comfortable outstation cabs, one-way drops, airport transfers, and customized holiday packages across India. Clean cabs, verified drivers, transparent per-km billing, and 24x7 customer support.',
  phone1: '7760466777',
  phone2: '7066651024',
  displayPhone1: '+91 77604 66777',
  displayPhone2: '+91 70666 51024',
  whatsappNumber: '917760466777',
  email: 'info@adviktoursandtravels.com',
  address: 'Shop No. 4, Sai Plaza, Opp. Central Bus Terminal, Hubli - Dharwad Highway, Karnataka 580020 / Pune Branch: Viman Nagar, Pune, Maharashtra 411014',
  workingHours: '24 Hours / 7 Days a Week',
  gstin: '29AABCA1234F1Z8',
  adminEmail: 'lakshmanchavan07@gmail.com',
};

export const DEFAULT_PRICING_RULES: PricingRules = {
  sedanRatePerKm: 12,
  suvRatePerKm: 15,
  tempoRatePerKm: 24,
  minKmPerDay: 300,
  sedanDriverAllowancePerDay: 300,
  suvDriverAllowancePerDay: 400,
  tempoDriverAllowancePerDay: 600,
  nightChargePerNight: 250,
  tollParkingPolicy: 'Toll, state taxes & parking charges are actuals to be paid by passenger.',
  gstPercentage: 5,
};

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'swift-dzire',
    name: 'Maruti Suzuki Dzire',
    category: 'sedan',
    capacityPassengers: 4,
    capacityLuggage: 2,
    acAvailable: true,
    fuelType: 'Diesel / CNG',
    ratePerKm: 12,
    minKmPerDay: 300,
    driverAllowancePerDay: 300,
    nightCharge: 250,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    features: ['Chilled AC', 'Bluetooth Audio', 'Fastag Enabled', 'Spacious Boot', 'Clean & Sanitized', 'First Aid Box'],
    isAvailable: true,
    status: 'active',
    displayOrder: 1,
    description: 'Most popular economy sedan for family outstation trips and business city rides. Excellent mileage and boot space.',
  },
  {
    id: 'toyota-etios',
    name: 'Toyota Etios',
    category: 'sedan',
    capacityPassengers: 4,
    capacityLuggage: 3,
    acAvailable: true,
    fuelType: 'Diesel',
    ratePerKm: 12,
    minKmPerDay: 300,
    driverAllowancePerDay: 300,
    nightCharge: 250,
    image: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80',
    features: ['Best-in-class Legroom', 'Huge Luggage Boot', 'Powerful Dual AC', 'Smooth Suspension', 'Fastag Enabled'],
    isAvailable: true,
    status: 'active',
    displayOrder: 2,
    description: 'Renowned for unmatched rear seat legroom and smooth highway cruising. Ideal for comfortable long distance journeys.',
  },
  {
    id: 'maruti-ertiga',
    name: 'Maruti Suzuki Ertiga',
    category: 'suv',
    capacityPassengers: 6,
    capacityLuggage: 3,
    acAvailable: true,
    fuelType: 'Diesel / Hybrid',
    ratePerKm: 15,
    minKmPerDay: 300,
    driverAllowancePerDay: 400,
    nightCharge: 300,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    features: ['6+1 Seater MUV', 'Dual Blower AC', 'Pushback Seats', 'Ample Luggage Carrier', 'Phone Charging Ports'],
    isAvailable: true,
    status: 'active',
    displayOrder: 3,
    description: 'Budget-friendly 6-seater family car with flexible seating and rooftop carrier options for luggage.',
  },
  {
    id: 'toyota-innova-crysta',
    name: 'Toyota Innova Crysta',
    category: 'suv',
    capacityPassengers: 7,
    capacityLuggage: 4,
    acAvailable: true,
    fuelType: 'Diesel',
    ratePerKm: 18,
    minKmPerDay: 300,
    driverAllowancePerDay: 400,
    nightCharge: 300,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    features: ['Captain Seats Option', 'Individual AC Vents', 'Superior Highway Ride', 'Premium Sound', 'Rooftop Carrier Available'],
    isAvailable: true,
    status: 'active',
    displayOrder: 4,
    description: 'The king of Indian highways. Uncompromised luxury, safety, and plush ride comfort for executive and family trips.',
  },
  {
    id: 'tempo-traveller-12',
    name: 'Force Tempo Traveller (12+1)',
    category: 'tempo_traveller',
    capacityPassengers: 12,
    capacityLuggage: 8,
    acAvailable: true,
    fuelType: 'Diesel',
    ratePerKm: 24,
    minKmPerDay: 300,
    driverAllowancePerDay: 600,
    nightCharge: 400,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    features: ['12 Reclining Pushback Seats', 'Dedicated Luggage Boot', 'LCD TV & Music System', 'High Roof Standing Space', 'Reading Lights'],
    isAvailable: true,
    status: 'active',
    displayOrder: 5,
    description: 'Ideal choice for group pilgrimage tours, wedding guest transfers, and corporate team excursions.',
  },
  {
    id: 'tempo-traveller-17',
    name: 'Force Luxury Traveller (17+1)',
    category: 'tempo_traveller',
    capacityPassengers: 17,
    capacityLuggage: 12,
    acAvailable: true,
    fuelType: 'Diesel',
    ratePerKm: 28,
    minKmPerDay: 300,
    driverAllowancePerDay: 650,
    nightCharge: 400,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80',
    features: ['17 Deluxe Pushback Seats', 'Full AC with individual vents', 'Spacious aisle', 'LED ambient lighting', 'Professional Chauffeur'],
    isAvailable: true,
    status: 'active',
    displayOrder: 6,
    description: 'Spacious luxury mini-bus for larger groups, family get-togethers, and long distance pilgrim circuits.',
  },
];

export const INITIAL_TOUR_PACKAGES: TourPackage[] = [
  {
    id: 'goa-sun-sand-heritage',
    title: 'Goa Coastal Sun & Heritage Explorer',
    destination: 'Goa (North & South)',
    durationDays: 3,
    durationNights: 2,
    startingPrice: 10499,
    vehicleType: 'Sedan / SUV / Tempo Traveller',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Experience the magic of Goa with complete sightseeing of pristine beaches, Portuguese cathedrals, Dudhsagar falls, and lively flea markets with dedicated private chauffeur.',
    placesCovered: ['Calangute & Baga Beach', 'Fort Aguada', 'Basilica of Bom Jesus', 'Old Goa Churches', 'Dona Paula', 'Miramar Beach', 'Mandovi River Cruise'],
    itinerary: [
      { day: 1, title: 'Arrival & North Goa Beaches', description: 'Pickup from home/airport, check-in to hotel. Visit Fort Aguada, Sinquerim, Calangute and lively Baga beach.' },
      { day: 2, title: 'South Goa Heritage & Churches', description: 'Explore Old Goa UNESCO churches, Mangueshi Temple, Dona Paula viewpoint and evening Mandovi sunset cruise.' },
      { day: 3, title: 'Spices & Shopping, Departure', description: 'Visit Sahakari spice plantation, local Panaji market, and return drop off in luxury vehicle.' },
    ],
    inclusions: ['Dedicated private AC vehicle with fuel', 'Driver allowance and night halts', 'Pickup and drop at your doorstep', 'Local sightseeing as per itinerary'],
    exclusions: ['Hotel accommodation (available on request)', 'Monument entry tickets & river cruise tickets', 'Personal meals, water & activities', 'Toll & parking fees'],
    terms: ['Booking advance 20% required for confirmation', 'Free cancellation up to 48 hours prior to trip', 'AC is turned off while vehicle is parked'],
    featured: true,
    status: 'active',
  },
  {
    id: 'shirdi-shani-shingnapur-darshan',
    title: 'Divine Shirdi & Shani Shingnapur Darshan',
    destination: 'Shirdi & Shani Shingnapur',
    durationDays: 2,
    durationNights: 1,
    startingPrice: 6999,
    vehicleType: 'Sedan (Swift Dzire) / SUV (Ertiga / Innova)',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'A peaceful, spiritually uplifting pilgrimage to Sai Baba Samadhi Mandir in Shirdi and the sacred Shani Shingnapur temple with courteous driver assistance.',
    placesCovered: ['Shirdi Sai Baba Samadhi Mandir', 'Dwarkamai', 'Chavadi', 'Gurusthan', 'Lendi Baug', 'Shani Shingnapur Temple'],
    itinerary: [
      { day: 1, title: 'Departure & Shirdi Evening Aarti', description: 'Early morning pickup. Scenic highway drive to Shirdi. Check-in, visit Samadhi Mandir for holy Darshan and attend Dhoop Aarti.' },
      { day: 2, title: 'Shani Shingnapur & Return', description: 'Morning Kakad Aarti / temple visit. Drive to Shani Shingnapur for oil abhishek. Comfortable return journey back home.' },
    ],
    inclusions: ['Private sanitized AC cab with experienced chauffeur', 'All driver allowances & fuel', 'Doorstep pickup and return drop', 'Assistance for senior citizens'],
    exclusions: ['VIP Darshan passes (direct purchase at trust counter)', 'Hotel stay', 'Meals & refreshments', 'Toll/parking charges'],
    terms: ['Early booking recommended for festival periods', 'Flexible start time as per your family convenience'],
    featured: true,
    status: 'active',
  },
  {
    id: 'mahabaleshwar-panchgani-escape',
    title: 'Mahabaleshwar & Panchgani Hill Station Retreat',
    destination: 'Mahabaleshwar & Panchgani',
    durationDays: 3,
    durationNights: 2,
    startingPrice: 8499,
    vehicleType: 'Sedan / SUV / Ertiga',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Escape into the misty Western Ghats. Breathe fresh strawberry aromas, scenic mountain viewpoints, serene Venna lake boating, and historic Pratapgad Fort.',
    placesCovered: ['Venna Lake', 'Arthur Seat Point', 'Pratapgad Fort', 'Mapro Garden', 'Table Land Panchgani', 'Old Mahabaleshwar Temple', 'Kate Point'],
    itinerary: [
      { day: 1, title: 'Ascend to Hills & Venna Lake', description: 'Morning pickup. Enjoy the scenic ghat road. Check-in at Mahabaleshwar. Evening boating at Venna Lake and local bazaar.' },
      { day: 2, title: 'Pratapgad Fort & Viewpoints', description: 'Visit historic Pratapgad Fort of Chhatrapati Shivaji Maharaj. Explore Arthur Seat, Elephant Head and Kate Point.' },
      { day: 3, title: 'Panchgani & Mapro Garden', description: 'Visit Table Land, Sydney Point, Mapro Garden for fresh strawberry treats, and comfortable return drive.' },
    ],
    inclusions: ['All vehicle transit, ghat driving by skilled hill driver', 'Driver allowance & fuel', 'Flexible stops for photos & snacks'],
    exclusions: ['Hotel stay', 'Entry fees, boating & horse rides', 'Food & snacks', 'Toll & municipality pollution entry tax'],
    terms: ['Experienced ghat-specialist drivers for complete safety', 'AC may be switched off on steep ghat inclines as per engine safety'],
    featured: true,
    status: 'active',
  },
  {
    id: 'mysore-coorg-heritage-nature',
    title: 'Mysore Royal Heritage & Coorg Coffee Haven',
    destination: 'Mysore & Coorg (Madikeri)',
    durationDays: 4,
    durationNights: 3,
    startingPrice: 13999,
    vehicleType: 'Sedan / Innova Crysta / Tempo Traveller',
    image: 'https://images.unsplash.com/photo-1600100397608-f010f4438df9?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600100397608-f010f4438df9?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Experience regal grandeur at Mysore Palace and immerse yourself in the lush coffee estates, waterfalls, and Tibetan monastery of Coorg.',
    placesCovered: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Dubare Elephant Camp', 'Namdroling Golden Temple', 'Abbey Falls', 'Raja Seat'],
    itinerary: [
      { day: 1, title: 'Mysore Palace & Brindavan Gardens', description: 'Pickup and drive to royal Mysore. Tour the magnificent Mysore Palace and evening illuminated fountain show at Brindavan Gardens.' },
      { day: 2, title: 'Drive to Coorg & Tibetan Golden Temple', description: 'Visit Chamundi Hill Temple, then drive to Coorg. Visit Bylakuppe Golden Temple (Namdroling) and check-in to coffee resort.' },
      { day: 3, title: 'Dubare Elephants & Abbey Falls', description: 'Morning visit to Dubare Elephant Camp, river rafting (seasonal), Abbey Falls and panoramic sunset at Raja Seat.' },
      { day: 4, title: 'Coffee Estate Tour & Return', description: 'Walk through fragrant spice and coffee plantations, shop authentic Coorg spices & chocolates, followed by return trip.' },
    ],
    inclusions: ['Private round-trip AC vehicle', 'Driver night stay & allowances', 'All intercity transfers & sightseeing', 'Doorstep pickup and drop'],
    exclusions: ['Hotel accommodation', 'Entry tickets, safari & rafting costs', 'Meals & personal expenses', 'Tolls & interstate taxes'],
    terms: ['Advance booking required', 'Best visited between September and May'],
    featured: false,
    status: 'active',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Rajesh Kulkarni',
    customerCity: 'Pune',
    bookingCode: 'ADV-2026-000042',
    tripType: 'Outstation to Goa',
    vehicleName: 'Toyota Innova Crysta',
    rating: 5,
    comment: 'Exceptional service by Advik Tours and Travels! The Innova Crysta was spotless, smelling fresh, and driver Mr. Ramesh was extremely polite and drove very safely across the ghats. No hidden charges whatsoever.',
    status: 'approved',
    createdAt: new Date('2026-08-15'),
  },
  {
    id: 'rev-2',
    customerName: 'Pooja Hegde',
    customerCity: 'Hubli',
    bookingCode: 'ADV-2026-000058',
    tripType: 'One Way Drop to Belgaum Airport',
    vehicleName: 'Swift Dzire',
    rating: 5,
    comment: 'Booked a one-way airport cab early at 4:30 AM. The driver arrived 15 minutes before time, helped with luggage, and we reached well ahead of boarding. Transparent per-km billing. Highly recommended!',
    status: 'approved',
    createdAt: new Date('2026-08-28'),
  },
  {
    id: 'rev-3',
    customerName: 'Anand Patil',
    customerCity: 'Kolhapur',
    bookingCode: 'ADV-2026-000071',
    tripType: 'Shirdi Pilgrimage Package',
    vehicleName: 'Maruti Ertiga',
    rating: 5,
    comment: 'Went on a 2-day Shirdi and Shani Shingnapur pilgrimage with elderly parents. The driver was so caring and patient with senior citizens, showing us the best Darshan gates. Truly grateful!',
    status: 'approved',
    createdAt: new Date('2026-09-02'),
  },
  {
    id: 'rev-4',
    customerName: 'Vikram Joshi',
    customerCity: 'Bangalore',
    bookingCode: 'ADV-2026-000089',
    tripType: 'Mysore & Coorg Tour',
    vehicleName: 'Tempo Traveller (12+1)',
    rating: 5,
    comment: 'Hired a 12-seater Tempo Traveller for our college reunion tour. Very comfortable pushback seats, great music system, clean interior, and great rates compared to others in the market.',
    status: 'approved',
    createdAt: new Date('2026-09-12'),
  },
];

// Pre-computed highway road distances (in KM) between key Indian cities for instant, high-accuracy calculation
export const KNOWN_DISTANCES: Record<string, number> = {
  // Hubli origins
  'hubli-bangalore': 415,
  'bangalore-hubli': 415,
  'hubli-pune': 430,
  'pune-hubli': 430,
  'hubli-goa': 155,
  'goa-hubli': 155,
  'hubli-belgaum': 98,
  'belgaum-hubli': 98,
  'hubli-dharwad': 22,
  'dharwad-hubli': 22,
  'hubli-kolhapur': 205,
  'kolhapur-hubli': 205,
  'hubli-mumbai': 580,
  'mumbai-hubli': 580,
  'hubli-hyderabad': 500,
  'hyderabad-hubli': 500,
  'hubli-mangalore': 345,
  'mangalore-hubli': 345,
  'hubli-shirdi': 590,
  'shirdi-hubli': 590,

  // Pune origins
  'pune-mumbai': 150,
  'mumbai-pune': 150,
  'pune-shirdi': 205,
  'shirdi-pune': 205,
  'pune-mahabaleshwar': 120,
  'mahabaleshwar-pune': 120,
  'pune-goa': 450,
  'goa-pune': 450,
  'pune-kolhapur': 235,
  'kolhapur-pune': 235,
  'pune-lonavala': 65,
  'lonavala-pune': 65,
  'pune-nashik': 210,
  'nashik-pune': 210,
  'pune-aurangabad': 235,
  'aurangabad-pune': 235,
  'pune-alibaug': 140,
  'alibaug-pune': 140,

  // Mumbai origins
  'mumbai-shirdi': 245,
  'shirdi-mumbai': 245,
  'mumbai-mahabaleshwar': 260,
  'mahabaleshwar-mumbai': 260,
  'mumbai-goa': 590,
  'goa-mumbai': 590,
  'mumbai-lonavala': 85,
  'lonavala-mumbai': 85,
  'mumbai-nashik': 165,
  'nashik-mumbai': 165,
  'mumbai-kolhapur': 380,
  'kolhapur-mumbai': 380,

  // Bangalore origins
  'bangalore-mysore': 145,
  'mysore-bangalore': 145,
  'bangalore-coorg': 255,
  'coorg-bangalore': 255,
  'bangalore-ooty': 275,
  'ooty-bangalore': 275,
  'bangalore-tirupati': 250,
  'tirupati-bangalore': 250,
  'bangalore-goa': 560,
  'goa-bangalore': 560,
  'bangalore-chennai': 345,
  'chennai-bangalore': 345,
};

export const POPULAR_CITIES = [
  'Hubli',
  'Dharwad',
  'Belgaum',
  'Pune',
  'Mumbai',
  'Goa',
  'Bangalore',
  'Kolhapur',
  'Shirdi',
  'Mahabaleshwar',
  'Lonavala',
  'Panchgani',
  'Mysore',
  'Coorg (Madikeri)',
  'Tirupati',
  'Nashik',
  'Aurangabad / Sambhajinagar',
  'Hyderabad',
  'Mangalore',
  'Udupi',
  'Alibaug',
  'Satara',
  'Solapur',
  'Davanagere',
  'Shimoga',
];
